### ISSUE TITLE
What is the 'caffenet.npy'? How can I get the file?

### ISSUE THREAD

**Issue by GengMingjin2** [microsoft/SA-Siam#1]
Great work! Thanks for your wonderful code!
 I just try to run the training and I found that when to begin training, 
it would load a file named 'caffenet.npy'. Is it a pretrained AlexNet for the S-Net in the paper ? 
Hope for your reply. 
      Best Wishes!

**Comment by 77695** [comment]
LINK: https://pan.baidu.com/s/1bZAtBGIlhXi9myvgSnLmXQ
PASSWORD: w52d

**Comment by GengMingjin2** [comment]
@77695 Thank you!
